/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Controllers.LeaderboardController;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fuzzyrock
 */
public class LeaderboardWindow extends javax.swing.JDialog {

    /**
     * Creates new form LeaderboardWindow
     */
    LeaderboardController lbCon;
    public LeaderboardWindow(java.awt.Frame parent, boolean modal, LeaderboardController lbCon) {
        super(parent, modal);
        initComponents();
        
        //Sets Window properties.
        setEarlyWindowProperties();
        
        //Initialize controllers.
        this.lbCon = lbCon;
        
        //Updates window elements info.
        updateLeaderboardTable();
    }
    
    /**
     * Set early window properties like background color and Window title.
     */
    public void setEarlyWindowProperties(){
        getContentPane().setBackground(Color.BLACK);
        this.setTitle("Leaderboard");
    }
    
    /**
     * Creates a TableModel and sends it to the Leaderboard controller to add Players score.
     */
    public void updateLeaderboardTable(){
        String columns[] = {"Name", "Score", "Level"};
        DefaultTableModel table = new DefaultTableModel(null, columns);
        this.lbCon.updateLeaderboardTable(table);
        this.tableLeaderboard.setModel(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneLeaderboard = new javax.swing.JScrollPane();
        tableLeaderboard = new javax.swing.JTable();
        lblHighScoreTitle = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableLeaderboard.setBackground(new java.awt.Color(0, 0, 0));
        tableLeaderboard.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 51), null));
        tableLeaderboard.setForeground(new java.awt.Color(255, 255, 255));
        tableLeaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneLeaderboard.setViewportView(tableLeaderboard);

        lblHighScoreTitle.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblHighScoreTitle.setForeground(new java.awt.Color(255, 204, 51));
        lblHighScoreTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHighScoreTitle.setText("LEADERBOARD");

        buttonClose.setBackground(new java.awt.Color(0, 0, 0));
        buttonClose.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        buttonClose.setForeground(new java.awt.Color(255, 255, 255));
        buttonClose.setText("CLOSE");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(scrollPaneLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblHighScoreTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(buttonClose)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblHighScoreTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonClose)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JLabel lblHighScoreTitle;
    private javax.swing.JScrollPane scrollPaneLeaderboard;
    private javax.swing.JTable tableLeaderboard;
    // End of variables declaration//GEN-END:variables
}
