/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ShipController;
import Models.Bullet;
import Models.Ship;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;

/**
 *
 * @author Juan Camilo Muños, Luis Miguel Sanchez Pinilla
 */
public class PlayerStatusBarView extends javax.swing.JPanel {

    /**
     * Creates new form gameBar
     */
    private ShipController shipCon;
    
    //Status bar objects
    final int catSeparator = 600;
    final int xInitPostion = 18;
    final int yInitPosition = 10;
    final int itemSpaceSeparator = 20;
    
    //Graphical objects
    ArrayList<Ship> lives;
    ArrayList<Bullet> missiles;
    
    public PlayerStatusBarView() {
 
    }
    public PlayerStatusBarView(ShipController ship){
        initComponents();
        this.shipCon = ship;
        this.lives = new ArrayList<>();
        this.missiles = new ArrayList<>();
    }
    
    /**
     * retorna el tanque con sus consumibles 
     * @return ControllerTank
     */
    public ShipController getTanque() {
        return shipCon;
    }
    /**
     * destina el tanque que sera usado en el objeto
     * @param tanque a destinar
     */
    public void setTanque(ShipController tanque) {
       this.shipCon = tanque;
       repaint();
    }
    
    public void createLiveShapes(){
        this.lives.clear();
        int currentX = xInitPostion-8;
        //System.out.println("lives: "+this.shipCon.getLivesCount());
        for (int i = 0; i < this.shipCon.getLivesCount(); i++) {//cantidad de vidas en forma de tanque
            Ship ship = new Ship(currentX, yInitPosition);
            currentX += itemSpaceSeparator + ship.getShapes().get(0).getWidth();
            this.lives.add(ship);
        }
        //System.out.println("lives list: "+this.lives.size());
    }
    
    public void createMissileShapes(){
        this.missiles.clear();
        int currentX = catSeparator+itemSpaceSeparator;
        for (int i = 0; i < this.shipCon.getMissileCapacity(); i++) {
            Bullet bullet = new Bullet(currentX, yInitPosition, 8 , 15);
            bullet.addShape(currentX-7, yInitPosition+16, 20, 3);
            currentX -= itemSpaceSeparator + bullet.getShapes().get(0).getWidth();
            this.missiles.add(bullet);
        }
    }
    
    public void fillRenderer(Graphics2D renderer, ArrayList<Rectangle2D> shapes){
        for(Rectangle2D current : shapes){
            renderer.fill(current);
        }
    }
    
    public void renderPlayerLives(Graphics2D renderer){
        createLiveShapes();
        renderer.setColor(this.shipCon.getShipColor());
        int n = 0;
        for(Ship current : this.lives){
            //System.out.println("lives: "+n+" | x: "+current.getX()+", y: "+current.getY());
            fillRenderer(renderer, current.getShapes());
            n++;
        }
    }
    
    public void renderPlayerMissiles(Graphics2D renderer){
        createMissileShapes();
        renderer.setColor(Color.ORANGE);
        int n = 0;
        for(Bullet current : this.missiles){
            //System.out.println("missiles: "+n+" | x: "+current.getX()+", y: "+current.getY());
            fillRenderer(renderer, current.getShapes());
            n++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D playerLives = (Graphics2D) g;
        Graphics2D playerMissiles = (Graphics2D) g;
        
        renderPlayerLives(playerLives);
        renderPlayerMissiles(playerMissiles);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
